<?php
/**
 * Attendance Export Handler
 * Supports: csv, pdf (print dialog), excel (.xlsx via PhpSpreadsheet)
 */
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;

require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../middleware/AuthMiddleware.php';
require_once __DIR__ . '/../models/Attendance.php';

if (!isAdmin() && !isStaff()) {
    die("Unauthorized access.");
}

$format = $_GET['format'] ?? 'csv';
$filters = [
    'event_id'   => $_GET['event_id']   ?? null,
    'member_id'  => $_GET['member_id']  ?? null,
    'status'     => $_GET['status']     ?? null,
    'start_date' => $_GET['start_date'] ?? null,
    'end_date'   => $_GET['end_date']   ?? null,
];

$attendanceModel = new Attendance($pdo);
$logs            = $attendanceModel->getLog($filters);
$filename        = "attendance_report_" . date('Y-m-d_His');

// ============================================================
// CSV Export
// ============================================================
if ($format === 'csv') {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename=' . $filename . '.csv');

    $output = fopen('php://output', 'w');
    fputcsv($output, ['Event', 'Member Name', 'Date', 'Status', 'Time In', 'Time Out']);
    foreach ($logs as $log) {
        fputcsv($output, [
            $log['event_title'],
            $log['full_name'],
            $log['date'],
            $log['status'],
            date('h:i A', strtotime($log['created_at'])),
            !empty($log['time_out']) ? date('h:i A', strtotime($log['time_out'])) : '',
        ]);
    }
    fclose($output);
    exit;
}

// ============================================================
// Excel Export via PhpSpreadsheet
// ============================================================
if ($format === 'excel') {
    if (file_exists(__DIR__ . '/../vendor/autoload.php')) {
        require_once __DIR__ . '/../vendor/autoload.php';
    }

    if (!class_exists(Spreadsheet::class)) {
        die("Excel export library (PhpSpreadsheet) is not available on this server. Please run 'composer install' or use CSV export.");
    }

    $spreadsheet = new Spreadsheet();
    $sheet       = $spreadsheet->getActiveSheet();
    $sheet->setTitle('Attendance Report');

    // ---- Church letterhead (row 1-2) ----
    $sheet->mergeCells('A1:F1');
    $sheet->setCellValue('A1', "God's Family United Methodist Church – Attendance Report");
    $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(13);
    $sheet->getStyle('A1')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

    $sheet->mergeCells('A2:F2');
    $dateLabel = '';
    if (!empty($filters['start_date']) && !empty($filters['end_date'])) {
        $dateLabel = date('F j, Y', strtotime($filters['start_date']));
        if ($filters['start_date'] !== $filters['end_date']) {
            $dateLabel .= ' – ' . date('F j, Y', strtotime($filters['end_date']));
        }
    } else {
        $dateLabel = 'All Dates';
    }
    $preparedByName = $_SESSION['name'] ?? 'System Admin';
    $preparedByRole = $_SESSION['role_name'] ?? 'Administrator';
    $sheet->setCellValue('A2', "Period: {$dateLabel} | Generated By: {$preparedByName} ({$preparedByRole}) | Date: " . date('F j, Y h:i A'));
    $sheet->getStyle('A2')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
    $sheet->getStyle('A2')->getFont()->setSize(10)->setItalic(true);

    // ---- Column headers (row 4) ----
    $headers = ['#', 'Member Name', 'Event', 'Date', 'Status', 'Time In', 'Time Out'];
    $cols    = ['A','B','C','D','E','F','G'];
    $sheet->mergeCells('A1:G1');
    $sheet->mergeCells('A2:G2');

    foreach ($headers as $i => $header) {
        $cell = $cols[$i] . '4';
        $sheet->setCellValue($cell, $header);
    }

    // Style header row
    $headerStyle = [
        'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '2D3748']],
        'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'FFFFFF']]],
    ];
    $sheet->getStyle('A4:G4')->applyFromArray($headerStyle);

    // ---- Data rows ----
    $row = 5;
    foreach ($logs as $idx => $log) {
        $sheet->setCellValue('A' . $row, $idx + 1);
        $sheet->setCellValue('B' . $row, $log['full_name']);
        $sheet->setCellValue('C' . $row, $log['event_title']);
        $sheet->setCellValue('D' . $row, date('M d, Y', strtotime($log['date'])));
        $sheet->setCellValue('E' . $row, $log['status']);
        $sheet->setCellValue('F' . $row, date('h:i A', strtotime($log['created_at'])));
        $sheet->setCellValue('G' . $row, !empty($log['time_out']) ? date('h:i A', strtotime($log['time_out'])) : '—');

        // Alternate row shading
        if ($idx % 2 === 0) {
            $sheet->getStyle("A{$row}:G{$row}")->getFill()
                  ->setFillType(Fill::FILL_SOLID)
                  ->getStartColor()->setRGB('F7FAFC');
        }
        $row++;
    }

    // ---- Total row ----
    $sheet->setCellValue('A' . $row, 'Total Present');
    $sheet->mergeCells("A{$row}:D{$row}");
    $sheet->setCellValue('E' . $row, count($logs));
    $totalStyle = [
        'font' => ['bold' => true],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'EBF8FF']],
    ];
    $sheet->getStyle("A{$row}:G{$row}")->applyFromArray($totalStyle);

    // Auto-size columns
    foreach ($cols as $col) {
        $sheet->getColumnDimension($col)->setAutoSize(true);
    }

    // Output
    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header('Content-Disposition: attachment; filename="' . $filename . '.xlsx"');
    header('Cache-Control: max-age=0');

    $writer = new Xlsx($spreadsheet);
    $writer->save('php://output');
    exit;
}

// ============================================================
// PDF Export (print-dialog HTML)
// ============================================================
if ($format === 'pdf') {
    if (file_exists(__DIR__ . '/../vendor/autoload.php')) {
        require_once __DIR__ . '/../vendor/autoload.php';
    }

    $dateLabel = '';
    if (!empty($filters['start_date']) && !empty($filters['end_date'])) {
        $startStr = date('F j, Y', strtotime($filters['start_date']));
        $endStr   = date('F j, Y', strtotime($filters['end_date']));
        $dateLabel = ($filters['start_date'] === $filters['end_date']) ? $startStr : "{$startStr} – {$endStr}";
    } elseif (!empty($logs[0]['date'])) {
        $dateLabel = date('F j, Y', strtotime($logs[0]['date']));
    } else {
        $dateLabel = 'All Dates';
    }

    $eventLabel = (!empty($filters['event_id']) && !empty($logs[0]['event_title'])) ? $logs[0]['event_title'] : 'All Events';
    $preparedByName = htmlspecialchars($_SESSION['name'] ?? 'System Admin');

    $logoPath = __DIR__ . '/assets/images/logo.png';
    $logoSrc = file_exists($logoPath) ? 'data:image/png;base64,' . base64_encode(file_get_contents($logoPath)) : '';

    if (class_exists(\Dompdf\Dompdf::class) && (!isset($_GET['html']) || $_GET['html'] !== '1')) {
        $options = new \Dompdf\Options();
        $options->set('isRemoteEnabled', true);
        $options->set('defaultFont', 'Helvetica');
        $dompdf = new \Dompdf\Dompdf($options);

        $tableRowsHtml = '';
        $i = 1;
        foreach ($logs as $log) {
            $timeOut = !empty($log['time_out']) ? date('h:i A', strtotime($log['time_out'])) : '---';
            $timeIn = date('h:i A', strtotime($log['created_at']));
            $tableRowsHtml .= '<tr>';
            $tableRowsHtml .= '<td>' . $i++ . '</td>';
            $tableRowsHtml .= '<td><strong>' . htmlspecialchars($log['full_name']) . '</strong></td>';
            $tableRowsHtml .= '<td>' . htmlspecialchars($log['event_title']) . '</td>';
            $tableRowsHtml .= '<td>Present</td>';
            $tableRowsHtml .= '<td>' . $timeIn . '</td>';
            $tableRowsHtml .= '<td>' . $timeOut . '</td>';
            $tableRowsHtml .= '</tr>';
        }
        if (empty($logs)) {
            $tableRowsHtml = '<tr><td colspan="6" style="text-align:center;">No attendance records found.</td></tr>';
        }

        $pdfHtml = '
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                body { font-family: Helvetica, Arial, sans-serif; font-size: 11px; color: #333; line-height: 1.4; }
                .header { text-align: center; margin-bottom: 20px; }
                .logo { width: 65px; height: 65px; border-radius: 50%; }
                .report-title { font-size: 16px; font-weight: bold; margin-top: 10px; text-transform: uppercase; letter-spacing: 1px; }
                .sub-title { font-size: 10px; color: #555; margin-top: 4px; }
                table { width: 100%; border-collapse: collapse; margin-top: 15px; }
                th, td { border: 1px solid #333; padding: 7px 9px; text-align: left; font-size: 10px; }
                th { background-color: #f2f2f2; font-weight: bold; }
                .sig-table { width: 100%; border: none; margin-top: 35px; }
                .sig-table td { border: none; text-align: center; vertical-align: top; }
                .sig-line { border-bottom: 1px solid #000; width: 180px; margin: 30px auto 5px; }
                .footer-bar { margin-top: 40px; text-align: center; font-size: 8.5px; color: #777; border-top: 1px solid #ccc; padding-top: 8px; }
            </style>
        </head>
        <body>
            <div class="header">
                ' . ($logoSrc ? '<img src="' . $logoSrc . '" class="logo"><br>' : '') . '
                <div style="font-size:9px;color:#555;">The United Methodist Church</div>
                <div style="font-size:8px;color:#555;">South Nueva Ecija Philippine Annual Conference</div>
                <div style="font-size:12px;font-weight:bold;margin-top:2px;">God\'s Family United Methodist Church</div>
                <hr style="border:0;border-top:1.5px solid #000;margin-top:8px;">
                <div class="report-title">Attendance Report</div>
                <div class="sub-title"><strong>Scope:</strong> ' . htmlspecialchars($eventLabel) . ' &nbsp;|&nbsp; <strong>Date:</strong> ' . htmlspecialchars($dateLabel) . '</div>
            </div>

            <table>
                <thead>
                    <tr>
                        <th style="width:30px;">#</th>
                        <th>Member Name</th>
                        <th>Event</th>
                        <th>Status</th>
                        <th>Time In</th>
                        <th>Time Out</th>
                    </tr>
                </thead>
                <tbody>
                    ' . $tableRowsHtml . '
                </tbody>
            </table>

            <table class="sig-table">
                <tr>
                    <td>
                        Prepared by:
                        <div class="sig-line"></div>
                        <strong>' . $preparedByName . '</strong><br>
                        <span style="font-size:9px;color:#666;">' . htmlspecialchars($_SESSION['role_name'] ?? 'Administrator') . '</span>
                    </td>
                    <td>
                        Noted by:
                        <div class="sig-line"></div>
                        <strong>Reverend / Pastor</strong><br>
                        <span style="font-size:9px;color:#666;">Church Official</span>
                    </td>
                </tr>
            </table>

            <div class="footer-bar">
                God\'s Family United Methodist Church - Official Record | Generated on ' . date('F d, Y h:i A') . '
            </div>
        </body>
        </html>';

        $dompdf->loadHtml($pdfHtml);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
        $dompdf->stream($filename . '.pdf', ['Attachment' => false]);
        exit;
    }

    // HTML Print Fallback
    ?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Attendance Report - <?php echo htmlspecialchars($eventLabel); ?></title>
        <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 30px; color: #333; line-height: 1.5; }
            .print-header { text-align: center; margin-bottom: 30px; }
            .letterhead { display: flex; align-items: center; justify-content: center; gap: 20px; margin-bottom: 15px; }
            .logo { height: 80px; width: 80px; border-radius: 50%; object-fit: cover; }
            .church-info { text-align: center; }
            .report-title { font-size: 1.5rem; font-weight: bold; margin: 20px 0 5px; text-transform: uppercase; letter-spacing: 2px; }
            table { width: 100%; border-collapse: collapse; margin-top: 25px; }
            th, td { border: 1px solid #000; padding: 10px; text-align: left; font-size: 11pt; }
            th { background-color: #f2f2f2; font-weight: bold; }
            .no-print { margin-bottom: 20px; background: #f8fafc; padding: 15px; border-radius: 8px; border: 1px solid #e2e8f0; }
            .btn { padding: 8px 20px; cursor: pointer; border-radius: 5px; border: 1px solid #cbd5e0; background: white; font-weight: 600; }
            .btn-primary { background: #3182ce; color: white; border-color: #2b6cb0; }
            .print-footer { margin-top: 60px; }
            .signature-section { display: flex; justify-content: space-around; margin-top: 40px; }
            .signature-box { text-align: left; min-width: 250px; }
            .sig-line { border-bottom: 1px solid #000; width: 220px; margin: 40px 0 5px; }
            .sig-name { font-weight: bold; margin: 0; }
            .sig-title { font-size: 0.9rem; color: #666; margin: 0; }
            @page { margin: 0; }
            @media print { .no-print { display: none !important; } body { margin: 0; padding: 15mm 20mm; } }
        </style>
    </head>
    <body>
        <?php if (!isset($_GET['hidemenu']) || $_GET['hidemenu'] !== 'true'): ?>
        <div class="no-print">
            <button onclick="window.print()" class="btn btn-primary">Download / Print PDF</button>
            <button onclick="window.close();" class="btn">Close Window</button>
            <p style="font-size:0.8rem;margin-top:10px;color:#666;">Tip: Uncheck "Headers and footers" in your browser print settings to hide default page URLs.</p>
        </div>
        <?php endif; ?>

        <div class="print-header">
            <div class="letterhead">
                <img src="assets/images/logo.png" alt="Logo" class="logo">
                <div class="church-info">
                    <div style="font-size:9pt;color:#555;">The United Methodist Church</div>
                    <div style="font-size:8pt;color:#555;">South Nueva Ecija Philippine Annual Conference</div>
                    <div style="font-size:12pt;font-weight:800;color:#000;margin-top:2px;">God's Family United Methodist Church</div>
                </div>
            </div>
            <hr style="border:0;border-top:2px solid #000;">
            <div class="report-title">Attendance Report</div>
            <p style="margin-top: 5px; font-size: 0.95rem;">
                <strong>Scope:</strong> <?php echo htmlspecialchars($eventLabel); ?> &nbsp;|&nbsp; 
                <strong>Date:</strong> <?php echo htmlspecialchars($dateLabel); ?>
            </p>
        </div>

        <table>
            <thead>
                <tr>
                    <th style="width:40px;">#</th>
                    <th>Member Name</th>
                    <th>Event</th>
                    <th>Status</th>
                    <th>Time In</th>
                    <th>Time Out</th>
                </tr>
            </thead>
            <tbody>
                <?php $i = 1; foreach ($logs as $log): ?>
                <tr>
                    <td><?php echo $i++; ?></td>
                    <td><strong><?php echo htmlspecialchars($log['full_name']); ?></strong></td>
                    <td><?php echo htmlspecialchars($log['event_title']); ?></td>
                    <td>Present</td>
                    <td><?php echo date('h:i A', strtotime($log['created_at'])); ?></td>
                    <td><?php echo !empty($log['time_out']) ? date('h:i A', strtotime($log['time_out'])) : '---'; ?></td>
                </tr>
                <?php endforeach; ?>
                <?php if (empty($logs)): ?>
                    <tr><td colspan="6" style="text-align:center;">No attendance records found.</td></tr>
                <?php endif; ?>
            </tbody>
        </table>

        <div class="print-footer">
            <div class="signature-section">
                <div class="signature-box">
                    <p>Prepared by:</p>
                    <div class="sig-line"></div>
                    <p class="sig-name"><?php echo htmlspecialchars($_SESSION['name'] ?? 'System Admin'); ?></p>
                    <p class="sig-title"><?php echo htmlspecialchars($_SESSION['role_name'] ?? 'Administrator'); ?></p>
                </div>
                <div class="signature-box">
                    <p>Noted by:</p>
                    <div class="sig-line"></div>
                    <p class="sig-name">Reverend / Pastor</p>
                    <p class="sig-title">Church Official</p>
                </div>
            </div>
            <div style="margin-top:60px;text-align:center;font-size:0.8rem;color:#777;border-top:1px solid #eee;padding-top:10px;">
                God's Family United Methodist Church - Official Record | Generated on <?php echo date('F d, Y h:i A'); ?>
            </div>
        </div>
        <script>
            window.onload = function() { setTimeout(function() { window.print(); }, 500); };
        </script>
    </body>
    </html>
    <?php
    exit;
}
